"""
NovaTech KnowledgeHub — Guardrails Module
==========================================
Integrates NVIDIA NeMo Guardrails for enterprise-grade input/output safety.

Rails implemented:
  1. Jailbreak & Prompt Injection Detection — blocks attempts to bypass AI guidelines
  2. Off-Topic Filtering — restricts queries to company knowledge base topics
  3. Output Safety Check — ensures responses don't leak sensitive information

Usage:
  from app.guardrails import initialize_rails, guard

  # On startup
  initialize_rails()

  # Before processing a query
  blocked, response = guard(user_message)
  if blocked:
      return response  # Rail fired, skip RAG pipeline
"""

import os
import logfire
from nemoguardrails import RailsConfig, LLMRails

_rails: LLMRails | None = None
_CONFIG_DIR = os.path.join(os.path.dirname(__file__), "config")


def initialize_rails() -> None:
    """
    Initialize the NeMo Guardrails engine on application startup.
    Loads configuration from app/guardrails/config/ (config.yml, prompts.yml, rails.co).
    """
    global _rails
    try:
        with logfire.span("🛡️ Initializing NeMo Guardrails"):
            # Ensure the API key is set for the OpenAI-compatible client
            if "GROQ_API_KEY" in os.environ and "OPENAI_API_KEY" not in os.environ:
                os.environ["OPENAI_API_KEY"] = os.environ["GROQ_API_KEY"]
                
            config = RailsConfig.from_path(_CONFIG_DIR)
            _rails = LLMRails(config)
            logfire.info("NeMo Guardrails initialized successfully.")
    except Exception as e: 
        logfire.error(f"Failed to initialize NeMo Guardrails: {e}")
        logfire.warning("Guardrails DISABLED — all queries will pass through unfiltered.")
        _rails = None


async def guard_async(user_message: str) -> tuple[bool, str]:
    """
    Evaluate a user message against all configured guardrails (async version).

    Returns:
        tuple[bool, str]: (rail_fired, response)
            - If rail_fired is True, the message was blocked and `response`
              contains the guardrail's safe refusal message.
            - If rail_fired is False, `response` is empty and the query
              should proceed to the RAG pipeline.
    """
    if _rails is None:
        logfire.warning("Guardrails not initialized — passing through.")
        return False, ""

    try:
        with logfire.span("🛡️ Guardrails Evaluation", user_input=user_message):
            result = await _rails.generate_async(
                messages=[{"role": "user", "content": user_message}]
            )

            # NeMo Guardrails returns a response dict with 'content'
            # If a rail fires, it returns the rail's response directly
            # We detect this by checking if the response came from a rail
            response_content = result.get("content", "") if isinstance(result, dict) else str(result)

            # Check if the response was generated by a rail (not the main LLM)
            # Rails produce specific canned responses we defined in rails.co
            rail_responses = [
                "I'm NovaTech KnowledgeHub, your internal knowledge assistant",
                "I appreciate your creativity, but I'm designed to be a secure",
                "Hello! 👋 I'm KnowledgeHub AI",
                "You're welcome! Let me know",
            ]

            rail_fired = any(marker in response_content for marker in rail_responses)

            if rail_fired:
                logfire.info(f"🛡️ Rail fired — query blocked: {user_message[:80]}...")
                return True, response_content
            else:
                logfire.info("✅ Guardrails passed — query proceeding to RAG pipeline.")
                return False, ""

    except Exception as e:
        logfire.error(f"Guardrails evaluation failed: {e}")
        # Fail open — if guardrails crash, allow the query through
        # This prevents guardrail issues from blocking all queries
        return False, ""


def guard(user_message: str) -> tuple[bool, str]:
    """
    Synchronous guardrails evaluation.
    Uses NeMo Guardrails' synchronous generate() method directly,
    avoiding async/sync bridging issues in FastAPI worker threads.
    """
    if _rails is None:
        logfire.warning("Guardrails not initialized — passing through.")
        return False, ""

    try:
        with logfire.span("🛡️ Guardrails Evaluation", user_input=user_message):
            result = _rails.generate(
                messages=[{"role": "user", "content": user_message}]
            )

            response_content = result.get("content", "") if isinstance(result, dict) else str(result)

            # Rails produce specific canned responses we defined in rails.co
            rail_responses = [
                "I'm NovaTech KnowledgeHub, your internal knowledge assistant",
                "I appreciate your creativity, but I'm designed to be a secure",
                "Hello! 👋 I'm KnowledgeHub AI",
                "You're welcome! Let me know",
                "I'm sorry, I can't respond to that."  # Default NeMo Guardrails rejection
            ]

            rail_fired = any(marker in response_content for marker in rail_responses)

            if rail_fired:
                logfire.info(f"🛡️ Rail fired — query blocked: {user_message[:80]}...")
                return True, response_content
            else:
                logfire.info("✅ Guardrails passed — query proceeding to RAG pipeline.")
                return False, ""

    except Exception as e:
        logfire.error(f"Guardrails evaluation failed: {e}")
        # Fail open — if guardrails crash, allow the query through
        return False, ""

